{% set name = "frelatage" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/frelatage-{{ version }}.tar.gz
  sha256: 930b779f301ece276e7e28808ad76182612b6b99fb8acfaad04e1c6122f53387

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - numpy >=1.22.3,<2.0.0
    - pympler >=1.0.1,<2.0.0
    - python >=3.6,<4.0
    - timeout-decorator >=0.5.0,<0.6.0

test:
  imports:
    - frelatage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Rog3rSm1th/Frelatage
  summary: Frelatage is a coverage-based Python fuzzing library which can be used to fuzz python code.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
